services:
  - type: web
    name: fire-on-the-island
    runtime: static
    buildCommand: npm run build
    staticPublishPath: public
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
